### ISSUE TITLE
Unable to move

### ISSUE THREAD

**Issue by Jerenaux** [Tach-Yon/Kaetram#1]
The game loads just fine, but when I click a tile, nothing happens. In the console, I see "requested path to ...". There is no output in the server console. I haven't looked in details into the code so I don't know if this has yet to be implemented or not, but I though it'd be worth signaling!

**Comment by Tach-Yon** [comment]
I am still working on doing pathfinding and entity movement (animations are done) so I should have it all working by the end of today!

**Comment by Tach-Yon** [comment]
Finished the basic movement tonight, will be updating it fairly soon to encompass other entities and whatnot.
